### ISSUE TITLE
No rakefile found

### ISSUE THREAD

**Issue by samnissen** [samnissen/polariscope_2#28]
``` bash
$mina fresh:db
user@place's password:
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```

I would assume you'd have to run bundler before being able to do this anyway?

**Comment by jhulme** [comment]
Yeah bundler should have been run prior to this. This is a definite problem I've probably missed partly due to my test environment.
