### ISSUE TITLE
DRY up *_sync code in rake tasks for connecting to API

### ISSUE THREAD

**Issue by samnissen** [samnissen/polariscope_2#3]
The classes for getting data from the API:
- lib/tasks/sync_actions.rb
- lib/tasks/sync_browsers.rb
- lib/tasks/sync_selectors.rb
- lib/tasks/sync_sibling_relationships.rb
- lib/tasks/sync_object_types.rb

reuse code for creating the connection to the API.

This could be passed to another class or module that would be instantiated when needed.

**Comment by jhulme** [comment]
Hi @samnissen,

just a quick refresher on this one, to confirm was it the following items you were looking to have cleaned up?

``` ruby
# action_sync.rb
@activities_path = "/api/v1/activities.json"
@events_path = "/api/v1/java_script_event_types.json"
@email = YAML.load(ERB.new(File.read(Rails.root.join('config', 'web_action_api.yml'))).result)[Rails.env]['email']
@token = YAML.load(ERB.new(File.read(Rails.root.join('config', 'web_action_api.yml'))).result)[Rails.env]['token']
@format = 'json'
```

``` ruby
# browser_sync.rb
@path = "/api/v1/browser_types.json"
@email = YAML.load(ERB.new(File.read(Rails.root.join('config', 'web_action_api.yml'))).result)[Rails.env]['email']
@token = YAML.load(ERB.new(File.read(Rails.root.join('config', 'web_action_api.yml'))).result)[Rails.env]['token']
@format = 'json'`
```

**Comment by samnissen** [comment]
@jhulme Yes, the `*_sync.rb` tasks shouldn't need to be passed the email, token and format for each task. I assume the best path is to move this to the email, token and format to the APIConnection class, then improving the `request` function. But I'm open to whatever comes naturally.
